### ISSUE TITLE
Map: show points (rather than hexagons) at high zoom level + popup

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#15]

**Comment by peterdesmet** [comment]
This is implement for https://alert.riparias.be/, see there for inspiration and source code.

<img width="317" alt="Screenshot 2022-09-15 at 13 42 11" src="https://user-images.githubusercontent.com/600993/190394865-3febba18-47bf-4ded-aab0-cccde8f1828d.png">

**Comment by niconoe** [comment]
Update: this is now implemented and visible on https://mica-uat.inbo.be/

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,

Looks good already, although I would work with a different colour than red, maybe the same blue as the left side of the dashboard. I would also make the points slightly see-trough. The link to GBIF is usefull, however I think the pop-up could show the number of individuals and the source data set as well.

**Comment by niconoe** [comment]
@EmmaCartuyvels1: I implemented your suggestions above, don't hesitate to have a look!

**Comment by EmmaCartuyvels1** [comment]
@niconoe looks good! You can push this to the actual dashboard

**Comment by niconoe** [comment]
This is done, thanks for the feedback!
