### ISSUE TITLE
What about incomplete dates

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#2]
That happens in [Muskrat captures in Flanders, Belgium](https://www.gbif.org/dataset/b7ee2a4d-8e10-410f-a951-a7f032678ffe) (year only)

- The current solution is to assign them to the first day of the year, which is imperfect.

Some possible approaches at: https://stackoverflow.com/questions/2971198/how-to-deal-with-partial-dates-2010-00-00-from-mysql-in-django and https://softwareengineering.stackexchange.com/questions/194286/how-do-you-store-fuzzy-dates-into-a-database

Might be useful to store all occurrence dates as range (when querying, see if occurrence range and query range overlap?)

**Comment by peterdesmet** [comment]
Note that this can affect the assignment to a occurrence over time chart: #22
