### ISSUE TITLE
Show trend over time

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#22]
That's an important feature for all partners. Some ideas about how to implement in practice:

- Use a date range slider in filters, so visitors can manually adjust the time and see related occurrences (+1 by Dolf)
- Show trend on at the municipality/river basin resolution:
    - how exactly do we show the data? timeline? something else?
    - data source: the easiest is probably to infer the municipality/basin from the coordinates
- show trend on a grid (for example, colour hexagons with a diverging scale showing if the population is increasing/decreasing in a given grid cell)

At first look, it appears those three approaches are complementary and should ideally all 3 be implemented.

**Comment by niconoe** [comment]
Dolf gave details over email about how the "trend grid" (point 3 above) should work::

a) Trend of the period selected under 1. compared to the same (= previous) period 1 year earlier
-    Three basic colors, for example green, red and white. White is (approximately) the same as previous period, red and green become darker as the difference is greater (indicate value in legend)

b) Trend of the period selected under 1. compared to 3 to 5 years (adjustable?) Before
-    Three basic colors, for example green, red and white. White is constant catches, the colored values ​​are explained in the legend

**Comment by niconoe** [comment]
Another possible approach: simple linear regression (can be implemented in pure SQL)?

**Comment by niconoe** [comment]
Emma comment: To be implemented soon, but not the highest priority neither.

**Comment by peterdesmet** [comment]
Cf. https://alert.riparias.be/ show observations (y-axis) over time (x-axis) for the currently selected data:

<img width="1125" alt="Screenshot 2022-09-15 at 13 35 34" src="https://user-images.githubusercontent.com/600993/190393687-725b0ced-74cf-4e8c-821b-fa5f78680b63.png">

**Comment by niconoe** [comment]
This is fixed now!

Do you think this feature is complete now?
