### ISSUE TITLE
Implement date slider

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#24]
(it's a first basis to show trend)

**Comment by niconoe** [comment]
That might also cover/replace/go in tandem with #19

**Comment by niconoe** [comment]
Basic mechanism in place (`date_range_filter` branch).

Next steps:

- Nice slider instead of two HTML date fileds
- Set boundaries of the slider based on data (min/max date of occurrences)

**Comment by niconoe** [comment]
Update: It's now merged into main and visible on the test site, but needs the improvements above (+ possibly bugfixes and more polishing)

**Comment by niconoe** [comment]
consider nouislider? create a thin vue wrapper around it?

**Comment by niconoe** [comment]
Ideally something like https://github.com/oguzhaninan/vue-histogram-slider would be even better

**Comment by niconoe** [comment]
@EmmaCartuyvels1: we can now select a start and end date for all searches. It might need improvements (a more user-friendly interface maybe), can you have a look.

I think playing with those filters can also be a first way to visualize the trend (I think we got feedback asking for such features).

**Comment by EmmaCartuyvels1** [comment]
Hi @niconoe, I think implementing some type of trend visualisation (can be a seperate graph) is definitely something we need to add

**Comment by peterdesmet** [comment]
Current start date / end data form is sufficient, but need to show observations over time, see issue #22.
