### ISSUE TITLE
Make hexagons transparent

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/mica-dashboard#27]
Get option full colour or transparent

**Comment by niconoe** [comment]
Thanks for the request, @EmmaCartuyvels1!

I'd like just a bit more context to implement as good as possible: what's the end goal here? Better visibility of the base map? Something else?

**Comment by EmmaCartuyvels1** [comment]
You are correct, it's better visibility of the base map

**Comment by niconoe** [comment]
I've implemented an opacity slider to allows dynamically changing the transparency, can you have a look? (at http://mica-uat.inbo.be/)

**Comment by EmmaCartuyvels1** [comment]
It works well, only one minor lay-out problem: you can't slide all the way to the left or right which is a bit odd but off course doesn't impact the functionality

**Comment by niconoe** [comment]
Thanks @EmmaCartuyvels1. Indeed, there was a small issue I was able to fix.
