### ISSUE TITLE
Add introduction

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/mica-dashboard#28]
Hi Nico, can you add the following introduction:

This dashboard attempts to give an overview of all muskrat and coypu observations (both catches and field observations) in Flanders, the Netherlands and certain areas in Germany. This dashboard is part of the LIFE MICA project, in which innovative techniques are tested for a more efficient control of muskrat and coypu populations, both invasive species. This dashboard will strengthen cooperation between neighboring countries because information on the presence of muskrats and coypu will be readily shared and used to inform management decisions.

**Be careful when interpreting the data! Not all data is updated regularly and more recent data may therefore be incomplete.**

This dashboard was created as part of the MICA project, which received funding from the European Union’s LIFE Environment sub-programme under the grant agreement LIFE18 NAT/NL/001047. (this part can be a bit smaller at the bottom)

**Comment by niconoe** [comment]
Sure, will do that soon!
