### ISSUE TITLE
Data download: all data for species X and Y in countries W and Z

### ISSUE THREAD

**Issue by niconoe** [inbo/mica-dashboard#34]
- Similar to what we do for RIPARIAS
- the approach seems sound, but currently we would only gain around 500 records
- An important feature of MICA is to distinguish observations VS catches. According to Emma, we could have an hardcoded list of cathes datasets, all the reste would be considered as an observation.
- Another think to check: is it okay to get all data for Belgium, Netherland and Germany, or should we filter per region? If so, can we do that filtering in the GBIF query, or should we implement our own filtering (against a shapefile?) in the import script?

(to be confirmed/rediscussed once with Emma before jumping to implementation)

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,
I think this is a really good idea!
We should get all the data from Flanders, the Netherland and Germany, but an additional feature can be that we filter for observations in our project areas (I have send you those shapefiles, correct?)
However I see that as another step that is not as urgent as implementing this

**Comment by niconoe** [comment]
Note to self: check how we can request data for **Flanders** (rather than Belgium) at GBIF.

If not easy/possible: alternative options are:

- load all data for Belgium
- filter out at import time in MICA

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,
Loading all data from Belgium would be fine as well!

**Comment by niconoe** [comment]
@EmmaCartuyvels1 : I'm in the process of implementing this! Could you give me the list of GBIF datasets that contains catches (occurrences found in those datasets will be considered as catches, all the others as observations)? 

thanks

Note to self: afterwards, update `GBIF_CATCHES_DATASET_KEY` in settings and test it's taken into account at import time.

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,
These datasets contain only catches:

- MICA - Muskrat occurrences collected by VMM in Flanders, Belgium
- [MICA - Muskrat occurrences collected by RATO in East Flanders, Belgium](https://www.gbif.org/dataset/95b0e787-8508-4247-9e48-18b45fc7d12e)
- [MICA - Muskrat and coypu occurrences collected by UVW in the Netherlands](https://www.gbif.org/dataset/45f54678-54ac-4468-8aac-bc83722fc768)
- [Mica - Muskrat, Raccoon and Coypu occurrences collected by ITAW in Germany](https://www.gbif.org/dataset/7dc4507b-63b7-4579-bd29-c5950018895b)
- [Muskrat captures in Flanders, Belgium](https://www.gbif.org/dataset/b7ee2a4d-8e10-410f-a951-a7f032678ffe)
- [Muskrat trapping data in the Netherlands 1987 – 2014](https://www.gbif.org/dataset/7d75109d-a6cb-4e90-89d0-79d08577c580)

However, in the future trapped and observed muskrats will be published together, at least for VMM.
Maybe it's good to discuss this with @damianooldoni who is publishing the data

**Comment by damianooldoni** [comment]
Indeed, as rattenapp is collecting also data about IAS plants relevant for LIFE RIPARIAS we decided to take care of the mapping to DwC and publication of catches (relevant for LIFE MICA) AND observations/eradication (plants and animals).

The dataset mapping in repo [riparias/vmm-rattenapp-occurrences](https://github.com/riparias/vmm-rattenapp-occurrences) is not far from being published (I am adding the catches of 2021 in a branch, almost done). In a second step (planned for June 2022) I would like to add the possibility to get an automated or semi automated workflow based on automatic export got via mail (VMM can set automatic mails with export it seems), GitHub Actions for running the DwC mapping and pywhip to allow some checks (via whip specs) which could trigger manual interventions if something new/suspect ocurrs in the DwC output.

**Comment by damianooldoni** [comment]
Title of this new dataset: "Rat control occurrences collected by VMM in Flanders, Belgium".
The dataset "MICA - Muskrat occurrences collected by VMM in Flanders, Belgium" will be therefore not updated anymore as catches will be included in the new more general dataset.

**Comment by damianooldoni** [comment]
Yes @niconoe, I confirm what I briefly said during a coffie break, last Tuesday.

We are going to publish https://github.com/riparias/vmm-rattenapp-occurrences using `samplingProtocol` = `"rat trap"`  for catches only. For observations: `samplingProtocol` = `"casual observation"`, while for eradication (plants) `samplingProtocol` = `"eradication"`. See https://github.com/riparias/vmm-rattenapp-occurrences/blob/add-catches/sql/dwc_occurrence.sql#L15-L19

**Comment by niconoe** [comment]
That's now implemented with the new import script
