### ISSUE TITLE
Show either catches or catch per km waterway

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/mica-dashboard#42]
I was going through the project proposal and noticed that this is also one of the requirements for the dashboard. I would show this as number of catches per km waterway for each km²

**Comment by niconoe** [comment]
Hi @EmmaCartuyvels1: 

If I understand correctly, that would be a different map that shows 1x1km cells over Belgium. For each cell, we would show the number of catches divided by the length of waterways, is that correct?

Please note that I'll need source some GIS data (shapefile) for those waterways, preferably in Open Data. I found the following shapefiles https://www.atlas-belgique.be/index.php/en/resources/map-data/ from KUL/Belpo/ULiège. Do you think the "waterway" file is good for our use?

**Comment by peterdesmet** [comment]
Needed:

- Have waterway line layer
- Calculate number of km waterway per km2: x
- Calculate number of occurrences per km2: y
- Provide y/x in map with km2 grid

**Comment by niconoe** [comment]
Hi @EmmaCartuyvels1, I've started some work with the "waterways" file from atlas-belgique.be so I can already make progress! Here is a screenshot showing its content, as far as I understand it only contains navigable bodies of water, which might not been enough for MICA:

![image](https://user-images.githubusercontent.com/386387/207011055-5c5dae78-f3d8-409a-9ca0-74e20ced40fe.png)

Can you have a look and confirm if we need to find another source of data or not?

**Comment by EmmaCartuyvels1** [comment]
Hi Nicolas, we will need to work with a layer that includes all waterways and water bodies so this won't be enough

**Comment by niconoe** [comment]
@EmmaCartuyvels1: I've experimented with the data found at http://hydro.iis.u-tokyo.ac.jp/~yamadai/OSM_water/index.html and I think it might actually be used to assign a "water coverage score" to each 1km square:

![image](https://user-images.githubusercontent.com/386387/207592734-65a2ea0c-39ce-42c6-91f9-f045208d3c39.png)

(the water data is representend by highlighted "pixels", the red grid is the 1km fishnet and the background is standard openstreetmap for reference)

We could count the number/surface of pixels in each red square, and we'd have a decent approximation of how much inland water occupies it, n?o

**Comment by niconoe** [comment]
@peterdesmet: if you have some time :sweat_smile: , don't hesitate to give your input on that (those last two comments might be enough to grasp the situation)

**Comment by peterdesmet** [comment]
@niconoe to me http://hydro.iis.u-tokyo.ac.jp/~yamadai/OSM_water/index.html looks like an excellent source:

> OSM Water Layers is a global surface water data, generated by extracting surface water features from OpenStreetMap.

- Source data is open and probably of good quality (updated by community)
- We don't have juggle with multiple source and difficult calculations

Question

- The OSM water data in your image looks like raster with a certain opacity. Is it possible to derive real values per pixel?
- I understand that you want to calculate a water coverage for a square. Why the 1km "fishnet" though?

**Comment by EmmaCartuyvels1** [comment]
I've asked for some more details on the Dutch way of calculating this, since I do think they work with the length of the waterways. I'll update once I hear back from them.

**Comment by niconoe** [comment]
@peterdesmet:

Thanks for the feedback. Answers below:

- OSM water layers is indeed a raster data source. Each pixel covers roughly 90 meter on 55, so if my calculation is correct we can fit around 200 pixels in each of the 1 km square. By simply counting pixels, we could therefore calculate an 'inland water coverage score' between 0 and 200 for each square. Each pixel also provides a value (1: ocean, 2: lake, 3: major river, 4 canal, 5: small stream), so we could maybe improve our score calculation by adding some ponderation (1 pixel marked as major river would count for more than a pixel marked for a small stream). 
- For your second question, I was indeed confusing in my use of the grid/square/fishnet terminology, but itś pretty simple: the fishnet is the grid, and it contains 1km squares over our region of interest.

About the data source, I think we have 3 possible routes now:

- use the raster date from "OSM water layers", as described above
- wait for the Dutch team's answer to see if their calculation method is applicable here and better than our other approaches
- Apparently the OSM water layers also exist in vector format. That could give us even better results (precise surface percentage of inland water for each square), but it might be a bit more complex to manipulate than the raster version.

On my side, I think I'll focus more on the development side of the feature (make the dashboard able to show the squares and their score), and go back to the data question later, when things get a bit clearer.

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,

This was the answer from Dolf:
We only look at the bank length to be processed:
For ponds and lakes, the perimeter is taken.
For watercourses up to 6 meters wide, the single bank length is included (such a watercourse can be worked from one side. For watercourses that are wider than 6 meters, both banks are included.

**Comment by niconoe** [comment]
Thanks Emma!

Can you provide me  data to calculate this? I'd need:

- data in a GIS format (shapefile, geopackages, ...)
- covering Belgium, Germany and Netherlands
- that includes all water courses and **include width information**
- and also includes lakes/ponds

If you can find that it would be immensely helpful. In case we cannot find this data (I am especially unsure about the river width data), I can try a different approach such as what was discussed above. Another approach would be doing it "the Dutch way" but treating all rivers the same (irrespective of their width).

**Comment by niconoe** [comment]
Update: first implementation visible on https://mica-uat.inbo.be/

**Comment by niconoe** [comment]
Hi @EmmaCartuyvels1 : do you still have remarks and things to change for this feature? Otherwise I was thinking of closing the issue so get a better view of what is still left to do. Thanks!
