### ISSUE TITLE
Some bugs in the current version of the dashboard

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/mica-dashboard#45]
Hi Nico,

When trying the dashboard I ran into some issues:

- [x] there are two "Ondatra zibethicus" to select in species
- [x] when changing one parameter, for example species, the selected dates move
- [x]  I think it would be good if standard dates where set to the last full month, so now for example dates would be set from 1/6/22 to 30/6/22

**Comment by EmmaCartuyvels1** [comment]
> If I understand correctly, it would be better to completely disable this logic and only show the occurrences from the last month, irrespective of which species is selected (of course, the users would keep the possibility to adjust the range as they wish)?

Yes, that is exactly what I mean 😊

**Comment by niconoe** [comment]
The species issue should now be fixed at the data import level. (to be confirmed after the next daily import)

**Comment by niconoe** [comment]
Apparently, all is good now.
