### ISSUE TITLE
Update lay-out

### ISSUE THREAD

**Issue by EmmaCartuyvels1** [inbo/mica-dashboard#46]
Hi Nico,

Some small changes that I feel would work better as lay-out
- [x] have the black column on the left extend all the way up
- [x] change the colour of that column to the same blue used on the project website (https://lifemica.eu/)
- [x] put the logo in top right corner
- [x] Change title to: Muskrat and Coypu monitor

**Comment by niconoe** [comment]
I've implemented the requested changes:

![image](https://user-images.githubusercontent.com/386387/207611117-10879124-6e87-45c2-be93-45146fd01b14.png)

**Comment by EmmaCartuyvels1** [comment]
Hi Nico,

When I visit the website I get the old look again:
![image](https://user-images.githubusercontent.com/44839819/211332330-c58d738b-f03a-49ad-8601-563b3007c3de.png)

**Comment by niconoe** [comment]
Hi Emma, the recent changes are not yet visible on the production MICA website so for the moment they can only be seen on https://mica-uat.inbo.be/
